apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
  name: guestbook
spec:
  port:
    targetPort: 80
  subdomain: ""
  to:
    kind: Service
    name: guestbook-ui
    weight: 100
  wildcardPolicy: None
